### ISSUE TITLE
Remove "from job id *" from apex class names

### ISSUE THREAD

**Issue by FeldhackerChrisPFG** [seamusocionnaigh/eventmonitoringplus#5]
Love the Event Monitoring Plus dashboards, they are great, and Salesforce should incorporate these into the core app!

For the Apex Exception Analysis, most of the Apex class names are fine, but when the exception involves an apex job, then the class name appears as "'SomeClass' from job id 707ablahblah".  And since each job id is unique, even though errors appears in the same apex class multiple times, each entry is treated as distinct.

Screen shots:
![image](https://user-images.githubusercontent.com/69258451/228367361-42f125ef-2324-4a80-89f4-023c0a61c959.png)
![image](https://user-images.githubusercontent.com/69258451/228367416-cd691d52-6292-43b9-8856-6751aa952196.png)

The result is that it is more difficult to get an accurate picture of apex job failures.

Is it possible to remove the "from job id *" portion from the class names?

**Comment by seamusocionnaigh** [comment]
Sorry for the delayed reply on this.
Agreed, the issue is a major usability challenge.
The challenge is how to parse and reformat the error value on a row-by-row basis within SAQL at dashboard runtime.  It's costly and limited to a certain row limit.
It's possible to do in a CRM Analytics recipe, or, off-platform in Python before loading back into CRMA.
